global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']
        basic_auth:
          username: "admin"
          password: "5253ed6af23f4762b89cb0bc9ea4fb13"

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
